spring:
  application:
    name: ecommerce

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ncecom?serverTimezone=UTC
    username: scott
    password: scott

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

file:
  upload-dir: src/main/resources/static/uploads

server:
  servlet:
    jsp:
      init-parameters:
        development: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      nc13:
        ecommerce:
          repository: TRACE